---
title: "Selected Publications"
description: |
output: 
  distill::distill_article:
    toc: true
    theme: mytheme.css
   
---
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
<script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>


### Vaccination & Other Health-Related Behaviors and Beliefs

<div style="display: flex; justify-content: space-around">

**Lazić, A.**, Kalinova, K. N., Packer, J., Pae, R., Petrović, M. B., Popović, D., Sievert, D. E. C., & Stafford-Johnson, N. (2021). Social nudges for vaccination: How communicating herd behaviour influences vaccination intentions. *British Journal of Health Psychology*, *26*(4), 1219–1237. https://doi.org/10.1111/bjhp.12556


<div data-badge-popover="right" data-badge-type="donut" data-doi="doi.org/10.1111/bjhp.12556" data-condensed="true" data-hide-no-mentions="true" class="altmetric-embed"></div>

<span class="__dimensions_badge_embed__" data-doi="10.1111/bjhp.12556" data-legend="hover-right" data-style="small_circle"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

</div>

[[Open Data]](https://osf.io/zb7s3/)
[[Stage 1 Registered Report]](https://osf.io/jpku3) 

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
<font size="3">Objectives: This Registered Report attempted to conceptually replicate the finding that communicating herd immunity increases vaccination intentions (Betsch, et al., 2017, *Nat. Hum. Behav.*, 0056). An additional objective was to explore the roles of descriptive social norms (vaccination behaviour of others) and the herd-immunity threshold (coverage needed to stop disease transmission). Design: An online experiment with a 2 (herd-immunity explanation: present vs. absent) × 3 (descriptive norm: high vs. low vs. absent) × 2 (herd-immunity threshold: present vs. absent) between-subjects fractional design. Methods: Sample consisted of 543 people (aged 18–64) residing in the United Kingdom. Participants first received an explanation of herd immunity emphasising social benefits (protecting others) in both textual and animated-infographic form. Next, they were faced with fictitious information about the disease, the vaccine, their country’s vaccination coverage (80% or 20%), and the herd-immunity threshold (90%). Vaccination intention was self-rated. Results: Compared to the control, communicating social benefits of herd immunity was effective in increasing vaccination intentions (*F*(1,541) = 6.97, *p* = .009, Partial Eta-Squared = 0.013). Conclusion: Communicating the descriptive norm or the herd-immunity threshold alongside the herd-immunity explanation demonstrated no observable effect. Communicating social benefits of herd immunity increased self-reported vaccination intentions against a fictitious disease, replicating previous findings. Although this result is positive, the practical relevance may be limited. Further research into the effect of social nudges to motivate vaccination is required, particularly with respect to the recent pandemic context and varying levels of vaccine hesitancy.</font>
</details>

<br>
**Lazić, A.**, & Žeželj, I. (2021). A systematic review of narrative interventions: Lessons for countering anti-vaccination conspiracy theories and misinformation. *Public Understanding of Science*, *30*(6), 644–670. [https://doi.org/10.1177/09636625211011881](https://journals.sagepub.com/eprint/TMJJFRDISUCJPFQGPEW7/full)

[[Postprint PDF]](https://psyarxiv.com/g5r8z/) [[Open Data]](https://osf.io/4d5rp/)

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>

<font size="3">Even if a small portion of the population refuses vaccination due to anti-vaccination conspiracy theories or misinformation, this poses a threat to public health. We argue that addressing conspiracy theories with only corrective information is not enough. Instead, considering that they are complex narratives embedded in personal and cultural worldviews, they should be encountered with counternarratives. To identify existing narrative interventions aimed at countering anti-vaccination conspiracy theories and, more generally, map prerequisites for a narrative intervention to be successful, we present a systematic review of experimental effects of exposure to pro-vaccine narratives on a range of vaccination outcomes, based on 17 studies and 97 comparisons. We did not find any narrative interventions aimed directly at conspiracy theories. However, the review allowed us to make evidence-based recommendations for future research and for public communicators. This might help pro-vaccine communication match anti-vaccine communication in its potential to spread and go viral.</font>
</details>

<br>
Teovanović, P., Lukić, P., Zupan, Z., **Lazić, A.**, Ninković, M., Žeželj, I. (2021). Irrational beliefs differentially predict adherence to guidelines and pseudoscientific practices during the COVID-19 pandemic. *Applied Cognitive Psychology*, *35*(2), 486–496. https://doi.org/10.1002/acp.3770

[[Open Data]](https://osf.io/9njp3/)

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>

<font size="3">In the coronavirus “infodemic,” people are exposed to official recommendations but also to potentially dangerous pseudoscientific advice claimed to protect against COVID-19. We examined whether irrational beliefs predict adherence to COVID-19 guidelines as well as susceptibility to such misinformation. Irrational beliefs were indexed by belief in COVID-19 conspiracy theories, COVID-19 knowledge overestimation, type I error cognitive biases, and cognitive intuition. Participants (*N* = 407) reported (1) how often they followed guidelines (e.g., handwashing, physical distancing), (2) how often they engaged in pseudoscientific practices (e.g., consuming garlic, colloidal silver), and (3) their intention to receive a COVID-19 vaccine. Conspiratorial beliefs predicted all three outcomes in line with our expectations. Cognitive intuition and knowledge overestimation predicted lesser adherence to guidelines, while cognitive biases predicted greater adherence, but also greater use of pseudoscientific practices. Our results suggest an important relation between irrational beliefs and health behaviors, with conspiracy theories being the most detrimental.</font>
</details>

### Biases in Altruism and Cooperation

**Lazić, A.**, Purić, D., & Krstić, K. (2021). Does parochial cooperation exist in childhood and adolescence? A meta-analysis. *International Journal of Psychology*, *56*(6), 917–933. https://doi.org/10.1002/ijop.12791

[[Postprint PDF]](https://psyarxiv.com/uexmr) [[Open Data]](https://osf.io/f7uwz/)

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
<font size="3">Although previous meta-analytic evidence supports the existence of parochialism in cooperation among adults, the extent to which children and adolescents are more willing to incur a personal cost to benefit ingroups, compared to outgroups, is not yet clear. We provide the first meta-analysis on the existence and magnitude of parochialism in cooperation among pre-adults. Based on 20 experimental economics studies (*k* = 69, *N* = 5268, age = 3–19, 12 countries, published 2008–2019), a multilevel meta-analytic model revealed a small overall effect size indicating that children and adolescents were more cooperative towards ingroups (*d* = 0.22, 95% CI [0.07, 0.38]). A series of single-moderator analyses tested for the following conditions: participant age and sex; game type ([mini-]dictator game, prisoner's dilemma, public goods dilemma, trust game, ultimatum game); outcome interdependence; membership manipulation (between- vs. within-subjects); group type (natural vs. experimental); reward type (monetary vs. non-monetary); and country of the participant. Parochial cooperation did not vary with participants' age. Parochialism was larger in non-interdependent (dictator-type) compared to interdependent (bargaining and social dilemma) games. There were no moderating effects of group type, membership manipulation or reward type. To provide more data on how parochialism develops, primary studies should report age ranges more precisely and use more restricted age groups.</font>
</details>

<br>
Baucal, A., & **Lazić, A.** (2022). Selfish genes or selfish memes: The effect of genetic relatedness
versus value similarity on altruism. *Psihologija*. https://doi.org/10.2298/PSI211107009B

[[Open Data]](https://osf.io/a8vq2/)

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>

<font size="3">Two preregistered quasi-experiments disentangled the effects of selfish genes and selfish memes on participants’ self-reported willingness to help in hypothetical everyday-favor and life-or-death situations. Memes were operationalized as the perceived level of similarity in important attitudes and values between the person participating in the study and a selected target person, assessed and reported by the participant. In Study 1 (*N* = 761), altruism was highest for siblings, and then for cousins and nonkin; greater memetic similarity was also associated with greater altruism; and the interaction between the factors was not significant. In Study 2 (*N* = 841), conducted during the COVID-19 pandemic, altruism was highest for siblings, but the same for cousins and nonkin; the effect of memetic similarity was replicated; and the interaction term remained insignificant. Both studies controlled for a range of demographic and social relationship characteristics, suggesting a potentially relevant role of future contact probability and emotional closeness. We propose that, similarly to gene selfishness, meme selfishness can also bring about altruism: individuals would rather make a personal sacrifice to help memetically similar than dissimilar others because similar others have a higher chance of spreading the helper’s memes.

</font>
</details>

### Open Science

**Lazić, A.**, Lazarević Lj. B., Purić, D., & Žeželj, I. (2021). REPOPSI: The open repository of psychological instruments in Serbian. In N. Miljković, P. Pejović, & M. Cvetanović (Eds.), *Proceedings of the Third National Conference with International Participation titled Application of free software and open hardware PSSOH 2020* (pp. 51–56). University of Belgrade School of Electrical Engineering and Academic Mind. https://doi.org/10.5281/zenodo.4064293

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>

<font size="3">The Repository of Psychological Instruments in Serbian (REPOPSI; https://osf.io/5zb8p/), run by the Laboratory for Research of Individual Differences at the University of Belgrade and hosted on the Open Science Framework, is an open-access repository of psychological instruments. REPOPSI is a collection of over 130 instruments (e.g., scales, tests) commonly used in social and behavioral science research. Documented are Serbian, English and multilingual instruments, which can be used free of charge for non-commercial purposes (e.g., academic research or education). We argue that REPOPSI enables scientists to increase the efficiency of their research and the visibility of their output. We analyze REPOPSI’s commitment to ensure that its (meta)data is findable, accessible, interoperable, and reusable (the FAIR Data Principles)and its trustworthiness with respect to transparency, responsibility, user focus, sustainability, and technology (the TRUST principles). Finally, we describe how the FAIR and the TRUST principles will support the process of continuous improvement of REPOPSI.</font>
</details>

<br>
Parsons, S., Azevedo, F., Elsherif, M. M., ... **Lazić, A.**, ..., & Aczel, B. (2022). A community-sourced
glossary of open scholarship terms. *Nature Human Behaviour*. [https://doi.org/10.1038/s41562-021-01269-4](https://rdcu.be/cHsqM)

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>

<font size="3">Open scholarship has transformed research, introducing a host of new terms in the lexicon of researchers. The Framework of Open and Reproducible Research Training (FORRT) community presents a crowdsourced glossary of open scholarship terms to facilitate education and effective communication between experts and newcomers.</font>
</details>

[[Postprint PDF]](https://osf.io/preprints/metaarxiv/kdqcw)
